name: white_coin
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^1.0.3
  cloud_firestore: ^1.0.4
  firebase_auth: ^1.0.3
  firebase_analytics: ^7.1.1
  regexpattern: ^1.0.0
  email_validator: '^1.0.0'
  flutter_svg: ^0.21.0+1
  open_mail_app: ^0.1.1




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^1.1.7+1

flutter_native_splash:
  color: "#ffffff"
  image: images/logo_transparent.png
  android: true
  ios: true

flutter:
  uses-material-design: true
  assets:
    - images/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
